name: Maintenance
on: push
jobs:
  cleanup-images:
    name: cleanup-images
    runs-on: ubuntu-18.04
    steps:
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCR_JSON_KEY }}
        export_default_credentials: true
    - run: |
        gcloud auth configure-docker
    - name: CLEAN OLD BUILD IMAGES
      env:
        IMAGE: eu.gcr.io/cf-rabbitmq-core/ci
      run: |
        DATE=$(date -d "-1 week" '+%Y-%m-%d')
        C=0
        for digest in $(gcloud container images list-tags ${IMAGE} --limit=999999 --sort-by=TIMESTAMP \
          --filter="timestamp.datetime < '${DATE}'" --format='get(digest)'); do
          (
            set -x
            echo gcloud container images delete -q --force-delete-tags "${IMAGE}@${digest}"
          )
          C=C+1
        done
        echo "Deleted ${C} images in ${IMAGE}." >&2
    - name: CLEAN OLD BUILD IMAGES
      env:
        IMAGE: eu.gcr.io/cf-rabbitmq-core/ci-rabbit
      run: |
        DATE=$(date -d "-1 week" '+%Y-%m-%d')
        C=0
        for digest in $(gcloud container images list-tags ${IMAGE} --limit=999999 --sort-by=TIMESTAMP \
          --filter="timestamp.datetime < '${DATE}'" --format='get(digest)'); do
          (
            set -x
            echo gcloud container images delete -q --force-delete-tags "${IMAGE}@${digest}"
          )
          C=C+1
        done
        echo "Deleted ${C} images in ${IMAGE}." >&2
